services:
  php:
    build:
      context: ./docker
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: tail -f /dev/null

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
